name: intrack
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  outline_material_icons: ^0.1.0
  # url_launcher: ^4.0.3
  flutter_calendar: ^0.0.8
  flutter_calendar_carousel: ^1.3.18
  uri: ^0.11.3+1
  charts_flutter: ^0.8.0
  connectivity: 
  intl: ^0.15.7
  path_provider: ^1.3.0
  http: ^0.12.0+2
  firebase_messaging: ^5.1.4
  # cloud_firestore:
  flutter_staggered_grid_view: "0.3.0"
  shared_preferences:
  rxdart: ^0.21.0
  shimmer:
  carousel_pro: 1.0.0
  package_info: ^0.4.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  pie_chart: ^1.2.0
  sticky_headers: 0.1.8
  file_picker: 1.4.0+1
  image_picker: 0.6.1+4
  flutter_local_notifications:
  swipedetector: 1.2.0
  # webview_flutter: ^0.3.14+1
  webview_flutter:
  pin_code_text_field: 1.4.0
  # youtube_player_flutter: 4.1.0
  youtube_player_flutter: 6.0.3+2
  pinput: 0.1.10
  cached_network_image: 2.0.0
  # flutter_pdfview: ^1.0.0+10
  photo_view: 0.9.0
  image_gallery_saver: 1.2.2
  permission_handler: 4.4.0+hotfix.4
  dio: 3.0.9
  open_file:
  jitsi_meet: 0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"
  font_awesome_flutter: ^8.0.1
  flutter_slidable: "^0.5.3"
  url_launcher: ^5.0.3
  provider: ^4.0.4


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_icons:
  image_path: "assets/icon/icon.jpeg"
  android: true
  ios: true

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/imageplaceholder.png
   - assets/studentdashboard.json
   - assets/teacherdashboard.json
   - assets/schoolPlay.jpeg
   - assets/schoolPlay2.jpeg
   - assets/schoolPlay3.jpeg
   - assets/schoolPlay_3.jpeg
   - assets/sportsDay1.jpeg
   - assets/sportsGirlsMatch.jpeg
   - assets/prizeDistribution.jpeg
   - assets/extraCuricular.jpeg
   - assets/CollabrativePainting.jpeg
   - assets/annualFunction.jpeg
   - assets/primaryStudentSports.jpeg
   - assets/icon/goldMedal.jpeg
   - assets/icon/needsimprovement.jpg
   - assets/icon/defaultUser.png
   - assets/icon/lightbolt.png
   - assets/login_logo.png
   - assets/demokid.jpg
   - assets/demoteacher.jpg
   - assets/img/carvedStones.jpg
   - assets/dashboardIcons/homeworkIcon.png
   - assets/dashboardIcons/Homework.png
   - assets/dashboardIcons/Attendance.png
   - assets/dashboardIcons/Birthday.png
   - assets/dashboardIcons/Diary.png
   - assets/dashboardIcons/Gallery.png
   - assets/dashboardIcons/Holidays.png
   - assets/dashboardIcons/Leaves.png
   - assets/dashboardIcons/News.png
   - assets/dashboardIcons/Notice_Board.png
   - assets/dashboardIcons/Performance.png
   - assets/dashboardIcons/Reminder.png
   - assets/dashboardIcons/Social_Media.png
   - assets/dashboardIcons/Syllabus.png
   - assets/dashboardIcons/Time_Table.png
   - assets/launch_image.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
